include $(ROOT_PATH)/.config

MODULE_C_FLAGS := 

#额外添加目录和文件
MODULE_SUB_DIR :=  $(shell echo $(CONFIG_PLATFORM))
MODULE_SUB_C_FILE :=
MODULE_SUB_CPP_FILE :=

-include $(ROOT_PATH)/tool/make/makeModule
